apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-ecr-eks-deployment
  labels:
    app: test-ecr-eks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-ecr-eks
  template:
    metadata:
      labels:
        app: test-ecr-eks
    spec:
      containers:
        - name: test-ecr-eks
          image: 423313210448.dkr.ecr.us-east-1.amazonaws.com/test-ecr-eks:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000 # Should match the port your React app is running on