apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  labels:
    app: test-ecr-eks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-ecr-eks
  template:
    metadata:
      labels:
        app: test-ecr-eks
    spec:
      containers:
        - name: test-ecr-eks
          image: 211446123712.dkr.ecr.us-east-1.amazonaws.com/test-ecr-eks:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000 # Should match the port your React app is running on