apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-ecr-eks
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-ecr-eks
  template:
    metadata:
      labels:
        app: test-ecr-eks
    spec:
      containers:
      - name: test-ecr-eks
        image: 211446123712.dkr.ecr.us-east-1.amazonaws.com/test-ecr-eks:${{ github.sha }}
