apiVersion: v1
kind: Service
metadata:
  name: test-ecr-eks-service
spec:
  selector:
    app: test-ecr-eks
  sessionAffinity: None
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer