name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t elmaghrioumayma23/ouma-cicd-pipeline .
      
    - name: Login Dockerhub
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      
    - name: Push to Dockerhub
      run: docker push elmaghrioumayma23/ouma-cicd-pipeline
