name: react app deploy to EKS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Kubectl
      uses: azure/setup-kubectl@v2.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login To Amazon Ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build & Tag Docker Image
      run: |
        docker build -t react-app-ecr .
        docker tag react-app-ecr:latest 157931892911.dkr.ecr.us-east-1.amazonaws.com/test-ecr-eks:latest
        
    - name: Push Docker Image to ecr
      run: docker push 157931892911.dkr.ecr.us-east-1.amazonaws.com/test-ecr-eks:latest

    - name: Update Kube Config
      run: aws eks --region us-east-1 update-kubeconfig --name cluster-eks

    - name: Deploy To Eks
      run: kubectl apply -f Kubernetes/deploy.yml -f Kubernetes/service.yml
